# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd0f80b6fd56687271177d38964e33bd696ec797da37370f0c0798ceaee932b4f051e75a31f4bca4ee5d6db166249e47efd50bbdc591142a280acc814eed9d4f

test:
  secret_key_base: 13b3aab81b93bd56284a946d338e71c04490d28507cddaac9f35c34afc6922ba1e3f4ffb5545048f7938c3e2aee7047c4c576bab548f3a9717451e567fddf9b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
