---
language: ruby
rvm:
  - 1.9.3
  - jruby-19mode
  - rbx-2
  - 2.1.5
gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
script: "rake spec[main] && rake spec[survey] && rake spec[participant] && rake spec[participation]"
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-2